//Criado utilizando o REST Client
GET http://localhost:3000/api/students

###

POST http://localhost:3000/api/students
Content-Type: application/json

{
    "name": "Jaciel",
    "email": "jaciel@upf.br",
    "age": 19
}

###

PUT http://localhost:3000/api/students/62fe2543-7752-41a9-a7ad-1194656c2fde
Content-Type: application/json

{
    "name": "Atualizando o nome"

}


###

DELETE http://localhost:3000/api/students/1