//Criado utilizando o REST Client
GET http://localhost:3000/api/students

###

POST http://localhost:3000/api/students
Content-Type: application/json

{
    "name": "Jaciel",
    "email": "jaciel@upf.br",
    "age": 19
}

###

PUT http://localhost:3000/api/students/1

###

DELETE http://localhost:3000/api/students/1